name = "leanio"
version = "0.2.0"
defaultTargets = ["LeanIO"]
testDriver = "Tests"

[[lean_lib]]
name = "LeanIO"

[[lean_exe]]
name = "todos"
root = "Todos"
srcDir = "Examples"

[[lean_lib]]
name = "Tests"
globs = ["Tests.+"]
