name = "leanio"
version = "0.1.0"
defaultTargets = ["leanio"]
testDriver = "Tests"

[[lean_lib]]
name = "LeanIO"

[[lean_exe]]
name = "leanio"
root = "Main"

[[lean_lib]]
name = "Tests"
globs = ["Tests.+"]