name = "leanio"
version = "0.5.0"
defaultTargets = ["LeanIO"]
testDriver = "Tests"

[[lean_lib]]
name = "LeanIO"

[[lean_exe]]
name = "todos"
root = "Todos"
srcDir = "Examples"

[[lean_exe]]
name = "leanplay"
root = "Main"
srcDir = "Examples/LeanPlay"

[[lean_exe]]
name = "upload"
root = "Upload"
srcDir = "Examples"

[[lean_exe]]
name = "whoami"
root = "WhoAmI"
srcDir = "Examples/WhoAmI"

[[lean_lib]]
name = "Tests"
globs = ["Tests.+"]

[[lean_exe]]
name = "sumtest"
root = "SumServer"
srcDir = "Examples"
